schema_version = "1.0.0"

# ID must be unique and lower-case (no spaces)
id = "gv_point_cloud_exporter"
version = "0.1.2"
name = "PointCloud and Splat Exporter (.ply, .splat)"
tagline = "Export PointCloud and Splat data to PLY and SPLAT format"
maintainer = "Giancarlo Viali"
type = "add-on"

# Minimum Blender version that supports Extensions
blender_version_min = "4.2.0"

# License must be compatible with Blender (GPL)
license = ['SPDX:GPL-3.0-or-later']

# Optional: website, copyright, etc.
website = "https://giancarloviali.it"
tags = ["Import-Export"]

[permissions]
files = "Export files on disk"
network = "Send anonymous usage analytics to Plausible Analytics. (Opt-In)"
