schema_version = "1.0.0"

# ID must be unique and lower-case (no spaces)
id = "gv_point_cloud_exporter"
version = "0.0.4"
name = "PointCloud and Splat Exporter (.ply)"
tagline = "Export PointCloud and Splat data to PLY format"
maintainer = "Giancarlo Viali"
type = "add-on"

# Minimum Blender version that supports Extensions
blender_version_min = "4.2.0"

# License must be compatible with Blender (GPL)
license = ['SPDX:GPL-3.0-or-later']

# Optional: website, copyright, etc.
website = "https://giancarlo.vialing.it"
tags = ["Import-Export"]

[permissions]
files = "files"
